
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "10000:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    env_file:
      - postgres.env

volumes:
  postgres:
